name: pipeline
on: [push]
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - name: Output affected projects
        id: set-matrix
        run: ./.github/scripts/output-nx-affected.sh
        shell: bash

  verify:
    needs: matrix
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.verify.outputs.affected }}
    steps:
      - name: Check if matrix is empty
        id: verify
        run: |
          if [ "${{ matrix }}" = "[]" ]; then
            echo "::set-output name=affected::false"
          else
            echo "::set-output name=affected::true"
          fi

  lint-and-test:
    needs: 
      - matrix
      - verify
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - if: ${{ needs.verify.outputs.affected == 'true' }}
        name: Lint
        run: yarn nx lint ${{ matrix.project }}
