name: pipeline
on: [push]
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - name: Output affected projects
        id: set-matrix
        run: ./.github/scripts/output-nx-affected.sh
        shell: bash

  lint-and-test:
    needs: matrix
    if: ${{ needs.matrix.outputs.matrix != '{"project":\ []}' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - name: Lint
        run: yarn nx lint ${{ matrix.project }}
      - name: Test
        run: yarn nx test ${{ matrix.project }}
