name: pipeline
on: [push]
jobs:
  affected:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.affected.outputs.affected }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - name: Output affected projects
        id: affected
        run: ./.github/scripts/output-nx-affected.sh
        shell: bash

  lint-and-test:
    needs: affected
    if: ${{ needs.affected.outputs.affected != '{project:[]}' && needs.affected.outputs.affected != '' }}
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.affected.outputs.affected) }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - name: Lint
        run: yarn nx lint ${{ matrix.project }}
      - name: Test
        run: yarn nx test ${{ matrix.project }}
