name: pipeline
on: [push]
jobs:
  matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - name: Output affected projects
        id: set-matrix
        run: ./.github/scripts/output-nx-affected.sh
        shell: bash

  verify-affected:
    needs: matrix
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.verify.outputs.affected }}
    steps:
      - name: Check if matrix is empty
        run: |
          if [ ${#matrix[@]} -eq 0 ]; then
            echo "affected=false"
          else
            echo "affected=true"
          fi

  lint-and-test:
    needs: 
      - matrix
      - verify-affected
    runs-on: ubuntu-latest
    strategy:
      verify-affected: ${{ needs.verify-affected.outputs.affected }}
      matrix: ${{ fromJson(needs.matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - if: verify-affected.affected
        name: Lint
        run: yarn nx lint ${{ matrix.project }}
      